#!D:\Users\Public\project\Project_Oct_2023\MLOpsAWS\mopsenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
